# This provides integration into the travis-ci.org CI system. For a overview
# check http://about.travis-ci.org/docs/user/getting-started/
# 
# Some notes:
# - language is "C" because the travis chroot for python installs a non-repo
#   python3.3 from a PPA
sudo: required
dist: bionic
language: c
before_install:
 - sudo apt-get update
 - sudo apt-get build-dep unattended-upgrades
 - sudo apt-get install -y fakeroot python3-coverage pyflakes3 mypy
 - which python3
 - python3 --version
script:
  - dpkg-buildpackage -d -us -uc -rfakeroot
  - sudo dpkg -i ../unattended-upgrades_*.deb
  - sudo unattended-upgrades --help
