name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: static checks
      run: |
        sudo apt update
        sudo apt build-dep -y ./
        sudo apt install -y python3-pytest
        pytest-3
        # ensure running each test standalone works
        for f in test/test_*.py; do
            if [ "$(basename $f)" = "test_base.py" ]; then
                continue
            fi
            pytest-3 $f
        done
    - name: setup
      run: |
        sudo apt-get update
        sudo apt-get install distro-info autopkgtest git-buildpackage
    - name: build source
      run: gbp buildpackage -us -uc -S -d -nc --git-ignore-branch --git-prebuild=
    - name: autopkgtest
      # skipping tests is ok, virt-null is used because lxd keeps failing
      # with: "Timed out waiting for container to boot"
      run: sudo autopkgtest -U ../build-area/*.dsc -- null || [ $? == 2 ]
